id: I1FEEC13B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T12:33:49+00:00'
last_modified: '2022-06-07T16:38:32.858841+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30403
  title: རྩ་བ་སུམ་ཅུ་པའི་འགྲེལ་པ་ཕན་བདེའི་དགའ་ཆར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '1961':
      image_group_id: I6097
      title: ''
      total_pages: 128
      order: 1
      base_file: 1961.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
