id: P002967
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W30403
  title: རྩ་བ་སུམ་ཅུ་པའི་འགྲེལ་པ་ཕན་བདེའི་དགའ་ཆར
  author: ''
  volumes:
    6a3eafa69c1549fabde07080159015ea:
      image_group_id: I6097
      title: ''
      volume_number: 1
      total_pages: 128
      base_file: v001.txt
